using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RestaurantPos.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddCancelAndExpiryInfrastructure : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "SystemSettings" ADD COLUMN IF NOT EXISTS "ExpiryJobRunTime" character varying(10) NOT NULL DEFAULT '';
                ALTER TABLE "SystemSettings" ADD COLUMN IF NOT EXISTS "ExpiryNotifyRoles" character varying(100) NOT NULL DEFAULT '';
                ALTER TABLE "SystemSettings" ADD COLUMN IF NOT EXISTS "NearExpiryDays" integer NOT NULL DEFAULT 0;

                ALTER TABLE "StockBatches" ADD COLUMN IF NOT EXISTS "ExpiredWasteLogged" boolean NOT NULL DEFAULT FALSE;
                ALTER TABLE "StockBatches" ADD COLUMN IF NOT EXISTS "NearExpiryNotified" boolean NOT NULL DEFAULT FALSE;
                CREATE INDEX IF NOT EXISTS "IX_StockBatches_ExpiryDate" ON "StockBatches" ("ExpiryDate");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "CancelReasons" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Code" character varying(50) NOT NULL,
                    "Name" character varying(200) NOT NULL,
                    "NameAr" character varying(200) NOT NULL,
                    "RequiresNote" boolean NOT NULL,
                    "IsActive" boolean NOT NULL,
                    "SortOrder" integer NOT NULL,
                    "TenantId" uuid NULL,
                    CONSTRAINT "PK_CancelReasons" PRIMARY KEY ("Id")
                );

                CREATE INDEX IF NOT EXISTS "IX_CancelReasons_Code" ON "CancelReasons" ("Code");

                INSERT INTO "CancelReasons" ("Id", "Code", "Name", "NameAr", "RequiresNote", "IsActive", "SortOrder", "TenantId")
                VALUES
                    (1, 'CLIENT_CHANGED_MIND', 'Client changed mind', 'العميل غير رأيه', FALSE, TRUE, 1, NULL),
                    (2, 'WRONG_ORDER_ENTERED', 'Wrong order entered', 'تم إدخال طلب خاطئ', FALSE, TRUE, 2, NULL),
                    (3, 'CLIENT_LEFT', 'Client left', 'العميل غادر', FALSE, TRUE, 3, NULL),
                    (4, 'ALLERGY_CONCERN', 'Allergy concern', 'مشكلة حساسية', FALSE, TRUE, 4, NULL),
                    (5, 'ITEM_UNAVAILABLE', 'Item unavailable', 'المنتج غير متوفر', FALSE, TRUE, 5, NULL),
                    (6, 'OTHER', 'Other', 'سبب آخر', TRUE, TRUE, 6, NULL)
                ON CONFLICT ("Id") DO UPDATE
                SET
                    "Code" = EXCLUDED."Code",
                    "Name" = EXCLUDED."Name",
                    "NameAr" = EXCLUDED."NameAr",
                    "RequiresNote" = EXCLUDED."RequiresNote",
                    "IsActive" = EXCLUDED."IsActive",
                    "SortOrder" = EXCLUDED."SortOrder",
                    "TenantId" = EXCLUDED."TenantId";

                SELECT setval(
                    pg_get_serial_sequence('"CancelReasons"', 'Id'),
                    COALESCE((SELECT MAX("Id") FROM "CancelReasons"), 1),
                    true
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "WasteLogs" (
                    "Id" uuid NOT NULL,
                    "Category" integer NOT NULL,
                    "ItemId" uuid NULL,
                    "ItemName" character varying(200) NOT NULL,
                    "Quantity" numeric(10,3) NOT NULL,
                    "Unit" character varying(30) NOT NULL,
                    "Reason" character varying(500) NOT NULL,
                    "LoggedById" uuid NULL,
                    "LoggedByName" character varying(150) NULL,
                    "SourceOrderId" uuid NULL,
                    "SourceOrderItemId" uuid NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "TenantId" uuid NOT NULL,
                    CONSTRAINT "PK_WasteLogs" PRIMARY KEY ("Id")
                );

                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'WasteLogs' AND column_name = 'ProductName'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'WasteLogs' AND column_name = 'ItemName'
                    ) THEN
                        EXECUTE 'ALTER TABLE "WasteLogs" RENAME COLUMN "ProductName" TO "ItemName"';
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'WasteLogs' AND column_name = 'CancelledByName'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'WasteLogs' AND column_name = 'LoggedByName'
                    ) THEN
                        EXECUTE 'ALTER TABLE "WasteLogs" RENAME COLUMN "CancelledByName" TO "LoggedByName"';
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'WasteLogs' AND column_name = 'OrderId'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'WasteLogs' AND column_name = 'SourceOrderId'
                    ) THEN
                        EXECUTE 'ALTER TABLE "WasteLogs" RENAME COLUMN "OrderId" TO "SourceOrderId"';
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'WasteLogs' AND column_name = 'OrderItemId'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'WasteLogs' AND column_name = 'SourceOrderItemId'
                    ) THEN
                        EXECUTE 'ALTER TABLE "WasteLogs" RENAME COLUMN "OrderItemId" TO "SourceOrderItemId"';
                    END IF;
                END $$;

                ALTER TABLE "WasteLogs" ADD COLUMN IF NOT EXISTS "ItemId" uuid NULL;
                ALTER TABLE "WasteLogs" ADD COLUMN IF NOT EXISTS "ItemName" character varying(200) NOT NULL DEFAULT '';
                ALTER TABLE "WasteLogs" ADD COLUMN IF NOT EXISTS "Reason" character varying(500) NOT NULL DEFAULT '';
                ALTER TABLE "WasteLogs" ADD COLUMN IF NOT EXISTS "LoggedById" uuid NULL;
                ALTER TABLE "WasteLogs" ADD COLUMN IF NOT EXISTS "LoggedByName" character varying(150) NULL;
                ALTER TABLE "WasteLogs" ADD COLUMN IF NOT EXISTS "SourceOrderId" uuid NULL;
                ALTER TABLE "WasteLogs" ADD COLUMN IF NOT EXISTS "SourceOrderItemId" uuid NULL;

                UPDATE "WasteLogs"
                SET "ItemName" = 'Unknown'
                WHERE "ItemName" IS NULL OR btrim("ItemName") = '';

                UPDATE "WasteLogs"
                SET "Reason" = CASE
                    WHEN "Category" = 1 THEN 'Auto-detected expiry | انتهاء صلاحية تلقائي'
                    ELSE 'Legacy waste log'
                END
                WHERE "Reason" IS NULL OR btrim("Reason") = '';

                UPDATE "WasteLogs" w
                SET "ItemId" = oi."ProductId"
                FROM "OrderItems" oi
                WHERE w."ItemId" IS NULL
                  AND w."SourceOrderItemId" IS NOT NULL
                  AND oi."Id" = w."SourceOrderItemId";

                ALTER TABLE "WasteLogs" ALTER COLUMN "ItemName" TYPE character varying(200);
                ALTER TABLE "WasteLogs" ALTER COLUMN "ItemName" SET NOT NULL;
                ALTER TABLE "WasteLogs" ALTER COLUMN "Quantity" TYPE numeric(10,3) USING "Quantity"::numeric(10,3);
                ALTER TABLE "WasteLogs" ALTER COLUMN "Unit" TYPE character varying(30);
                ALTER TABLE "WasteLogs" ALTER COLUMN "Reason" TYPE character varying(500);
                ALTER TABLE "WasteLogs" ALTER COLUMN "Reason" SET NOT NULL;
                ALTER TABLE "WasteLogs" ALTER COLUMN "LoggedByName" TYPE character varying(150);

                ALTER TABLE "WasteLogs" DROP CONSTRAINT IF EXISTS "FK_WasteLogs_OrderItems_OrderItemId";
                ALTER TABLE "WasteLogs" DROP CONSTRAINT IF EXISTS "FK_WasteLogs_Orders_OrderId";
                ALTER TABLE "WasteLogs" DROP CONSTRAINT IF EXISTS "FK_WasteLogs_Users_LoggedById";

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_WasteLogs_OrderItems_SourceOrderItemId') THEN
                        EXECUTE 'ALTER TABLE "WasteLogs" ADD CONSTRAINT "FK_WasteLogs_OrderItems_SourceOrderItemId" FOREIGN KEY ("SourceOrderItemId") REFERENCES "OrderItems" ("Id") ON DELETE SET NULL';
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_WasteLogs_Orders_SourceOrderId') THEN
                        EXECUTE 'ALTER TABLE "WasteLogs" ADD CONSTRAINT "FK_WasteLogs_Orders_SourceOrderId" FOREIGN KEY ("SourceOrderId") REFERENCES "Orders" ("Id") ON DELETE SET NULL';
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_WasteLogs_Users_LoggedById') THEN
                        EXECUTE 'ALTER TABLE "WasteLogs" ADD CONSTRAINT "FK_WasteLogs_Users_LoggedById" FOREIGN KEY ("LoggedById") REFERENCES "Users" ("Id") ON DELETE SET NULL';
                    END IF;
                END $$;

                DROP INDEX IF EXISTS "IX_WasteLogs_OrderId";
                DROP INDEX IF EXISTS "IX_WasteLogs_OrderItemId";

                CREATE INDEX IF NOT EXISTS "IX_WasteLogs_LoggedById" ON "WasteLogs" ("LoggedById");
                CREATE INDEX IF NOT EXISTS "IX_WasteLogs_SourceOrderId" ON "WasteLogs" ("SourceOrderId");
                CREATE INDEX IF NOT EXISTS "IX_WasteLogs_SourceOrderItemId" ON "WasteLogs" ("SourceOrderItemId");
                CREATE INDEX IF NOT EXISTS "IX_WasteLogs_TenantId_Category_CreatedAt" ON "WasteLogs" ("TenantId", "Category", "CreatedAt");
                CREATE INDEX IF NOT EXISTS "IX_WasteLogs_TenantId_CreatedAt" ON "WasteLogs" ("TenantId", "CreatedAt");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "CancelLogs" (
                    "Id" uuid NOT NULL,
                    "OrderId" uuid NOT NULL,
                    "OrderItemId" uuid NULL,
                    "CancelledById" uuid NOT NULL,
                    "CancelledByName" character varying(150) NOT NULL,
                    "CancelledByRole" integer NOT NULL,
                    "OrderTime" timestamp with time zone NOT NULL,
                    "CancelledAt" timestamp with time zone NOT NULL,
                    "CancelReasonCode" character varying(50) NOT NULL,
                    "CancelReasonNote" character varying(500) NULL,
                    "WasteLogId" uuid NULL,
                    "TenantId" uuid NOT NULL,
                    CONSTRAINT "PK_CancelLogs" PRIMARY KEY ("Id")
                );

                ALTER TABLE "CancelLogs" ADD COLUMN IF NOT EXISTS "OrderId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
                ALTER TABLE "CancelLogs" ADD COLUMN IF NOT EXISTS "OrderItemId" uuid NULL;
                ALTER TABLE "CancelLogs" ADD COLUMN IF NOT EXISTS "CancelledById" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
                ALTER TABLE "CancelLogs" ADD COLUMN IF NOT EXISTS "CancelledByName" character varying(150) NOT NULL DEFAULT '';
                ALTER TABLE "CancelLogs" ADD COLUMN IF NOT EXISTS "CancelledByRole" integer NOT NULL DEFAULT 0;
                ALTER TABLE "CancelLogs" ADD COLUMN IF NOT EXISTS "OrderTime" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
                ALTER TABLE "CancelLogs" ADD COLUMN IF NOT EXISTS "CancelledAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
                ALTER TABLE "CancelLogs" ADD COLUMN IF NOT EXISTS "CancelReasonCode" character varying(50) NOT NULL DEFAULT '';
                ALTER TABLE "CancelLogs" ADD COLUMN IF NOT EXISTS "CancelReasonNote" character varying(500) NULL;
                ALTER TABLE "CancelLogs" ADD COLUMN IF NOT EXISTS "WasteLogId" uuid NULL;
                ALTER TABLE "CancelLogs" ADD COLUMN IF NOT EXISTS "TenantId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

                ALTER TABLE "CancelLogs" DROP CONSTRAINT IF EXISTS "FK_CancelLogs_OrderItems_OrderItemId";
                ALTER TABLE "CancelLogs" DROP CONSTRAINT IF EXISTS "FK_CancelLogs_Orders_OrderId";
                ALTER TABLE "CancelLogs" DROP CONSTRAINT IF EXISTS "FK_CancelLogs_Users_CancelledById";
                ALTER TABLE "CancelLogs" DROP CONSTRAINT IF EXISTS "FK_CancelLogs_WasteLogs_WasteLogId";

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CancelLogs_OrderItems_OrderItemId') THEN
                        EXECUTE 'ALTER TABLE "CancelLogs" ADD CONSTRAINT "FK_CancelLogs_OrderItems_OrderItemId" FOREIGN KEY ("OrderItemId") REFERENCES "OrderItems" ("Id") ON DELETE SET NULL';
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CancelLogs_Orders_OrderId') THEN
                        EXECUTE 'ALTER TABLE "CancelLogs" ADD CONSTRAINT "FK_CancelLogs_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE RESTRICT';
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CancelLogs_Users_CancelledById') THEN
                        EXECUTE 'ALTER TABLE "CancelLogs" ADD CONSTRAINT "FK_CancelLogs_Users_CancelledById" FOREIGN KEY ("CancelledById") REFERENCES "Users" ("Id") ON DELETE RESTRICT';
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CancelLogs_WasteLogs_WasteLogId') THEN
                        EXECUTE 'ALTER TABLE "CancelLogs" ADD CONSTRAINT "FK_CancelLogs_WasteLogs_WasteLogId" FOREIGN KEY ("WasteLogId") REFERENCES "WasteLogs" ("Id") ON DELETE SET NULL';
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS "IX_CancelLogs_CancelledById_CancelledAt" ON "CancelLogs" ("CancelledById", "CancelledAt");
                CREATE INDEX IF NOT EXISTS "IX_CancelLogs_OrderId" ON "CancelLogs" ("OrderId");
                CREATE INDEX IF NOT EXISTS "IX_CancelLogs_OrderItemId" ON "CancelLogs" ("OrderItemId");
                CREATE INDEX IF NOT EXISTS "IX_CancelLogs_TenantId_CancelledAt" ON "CancelLogs" ("TenantId", "CancelledAt");
                CREATE INDEX IF NOT EXISTS "IX_CancelLogs_WasteLogId" ON "CancelLogs" ("WasteLogId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "CancelLogs";
                DROP TABLE IF EXISTS "CancelReasons";
                """);
        }
    }
}
