namespace RestaurantPos.Api.Modules.Payments.Domain.ValueObjects;

/// <summary>
/// Stable business reference generated by the merchant side.
/// Kept as a value object so uniqueness and formatting rules are enforced before persistence.
/// </summary>
public sealed record MerchantReference
{
    /// <summary>Maximum length kept under common gateway limits while leaving room for branch/order prefixes.</summary>
    public const int MaxLength = 100;

    private MerchantReference()
    {
        Value = string.Empty;
    }

    /// <summary>Creates a normalized merchant reference.</summary>
    public MerchantReference(string value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value);

        var normalized = value.Trim();
        if (normalized.Length > MaxLength)
        {
            throw new ArgumentException($"Merchant reference cannot exceed {MaxLength} characters.", nameof(value));
        }

        if (normalized.Any(static c => !IsAllowedCharacter(c)))
        {
            throw new ArgumentException("Merchant reference contains unsupported characters.", nameof(value));
        }

        Value = normalized;
    }

    /// <summary>Normalized merchant-generated reference.</summary>
    public string Value { get; }

    private static bool IsAllowedCharacter(char value)
        => char.IsLetterOrDigit(value) || value is '-' or '_' or '.' or ':';

    /// <inheritdoc />
    public override string ToString() => Value;
}
