using System.Text;
using ClosedXML.Excel;
using RestaurantPos.Api.DTOs;
using RestaurantPos.Api.Modules.Dashboard.Services.Export;

namespace RestaurantPos.Api.Services
{
    public sealed class RawMaterialConsumptionExportService : IRawMaterialConsumptionExportService
    {
        private const string HeaderColor = "#0F766E";

        public DashboardExportFile BuildExcel(RawMaterialConsumptionReportDto report, IReadOnlyList<RawMaterialConsumptionDetailDto> details, RawMaterialConsumptionQueryDto query, string companyName, string? logoUrl, string generatedBy)
        {
            using var workbook = new XLWorkbook();
            WriteSummary(workbook, report, companyName, logoUrl, generatedBy);
            WriteDetails(workbook, details);
            WriteFilters(workbook, report, query, generatedBy);
            using var stream = new MemoryStream();
            workbook.SaveAs(stream);
            return new DashboardExportFile(stream.ToArray(), FileName("xlsx"), DashboardWorkbookWriter.ContentType);
        }

        public DashboardExportFile BuildCsv(IReadOnlyList<RawMaterialConsumptionDetailDto> details)
        {
            var csv = new StringBuilder("\uFEFFDate / التاريخ,Order No / رقم الطلب,Product / المنتج,Category / الفئة,Raw Material / المادة الخام,Recipe Qty / كمية الوصفة,Sold Qty / الكمية المباعة,Total Consumed / إجمالي الاستهلاك,Branch / الفرع,Order Type / نوع الطلب,Status / الحالة\r\n");
            foreach (var row in details)
                csv.AppendLine(string.Join(',', Csv(row.DeductedAtUtc.ToString("O")), Csv(row.OrderNumber), Csv(Bilingual(row.ProductName, row.ProductNameAr)), Csv(Bilingual(row.CategoryName, row.CategoryNameAr)), Csv(Bilingual(row.RawMaterialName, row.RawMaterialNameAr)), row.RecipeQuantity, row.SoldQuantity, row.TotalConsumed, Csv(Bilingual(row.BranchName, row.BranchNameAr)), Csv(row.OrderType), Csv(row.OrderStatus)));
            return new DashboardExportFile(Encoding.UTF8.GetBytes(csv.ToString()), FileName("csv"), "text/csv; charset=utf-8");
        }

        private static void WriteSummary(XLWorkbook workbook, RawMaterialConsumptionReportDto report, string companyName, string? logoUrl, string generatedBy)
        {
            var sheet = workbook.Worksheets.Add("Summary - الملخص");
            AddLogo(sheet, logoUrl);
            var rows = new (string, object?)[] { ("Company / الشركة", companyName), ("Report / التقرير", "Raw Material Consumption / استهلاك المواد الخام"),
                ("Raw Material / المادة الخام", Bilingual(report.RawMaterialName, report.RawMaterialNameAr)),
                ("Period / الفترة", $"{report.FromUtc:u} - {report.ToUtc:u}"), ("Branch / الفرع", Bilingual(report.BranchName, report.BranchNameAr)), ("Generated by / أنشئ بواسطة", generatedBy),
                ("Generated / تاريخ الإنشاء", DateTime.UtcNow), ("Total consumed / إجمالي الاستهلاك", report.TotalConsumed),
                ("Orders / الطلبات", report.OrderCount), ("Products / المنتجات", report.ProductCount), ("Categories / الفئات", report.CategoryCount),
                ("Average daily / المتوسط اليومي", report.AverageDailyConsumption), ("Average per order / متوسط الطلب", report.AverageConsumptionPerOrder) };
            for (var i = 0; i < rows.Length; i++) { sheet.Cell(i + 1, 1).Value = rows[i].Item1; SetValue(sheet.Cell(i + 1, 2), rows[i].Item2); }
            var rowIndex = rows.Length + 2;
            Headers(sheet, rowIndex++, "Product / المنتج", "Category / الفئة", "Orders / الطلبات", "Sold / المباع", "Recipe / الوصفة", "Consumed / المستهلك", "%");
            foreach (var row in report.Products) { sheet.Cell(rowIndex, 1).Value = Bilingual(row.ProductName, row.ProductNameAr); sheet.Cell(rowIndex, 2).Value = Bilingual(row.CategoryName, row.CategoryNameAr); sheet.Cell(rowIndex, 3).Value = row.OrderCount; sheet.Cell(rowIndex, 4).Value = row.QuantitySold; sheet.Cell(rowIndex, 5).Value = row.RecipeQuantityPerProduct; sheet.Cell(rowIndex, 6).Value = row.TotalConsumed; sheet.Cell(rowIndex++, 7).Value = row.Percentage; }
            rowIndex++;
            Headers(sheet, rowIndex++, "Category / الفئة", "Orders / الطلبات", "Consumed / المستهلك", "%");
            foreach (var row in report.Categories) { sheet.Cell(rowIndex, 1).Value = Bilingual(row.CategoryName, row.CategoryNameAr); sheet.Cell(rowIndex, 2).Value = row.OrderCount; sheet.Cell(rowIndex, 3).Value = row.TotalConsumed; sheet.Cell(rowIndex++, 4).Value = row.Percentage; }
            Format(sheet);
        }

        private static void WriteDetails(XLWorkbook workbook, IReadOnlyList<RawMaterialConsumptionDetailDto> details)
        {
            var sheet = workbook.Worksheets.Add("Detailed Consumption - التفاصيل");
            Headers(sheet, 1, "Date / التاريخ", "Time / الوقت", "Order No / رقم الطلب", "Product / المنتج", "Category / الفئة", "Raw Material / المادة الخام", "Recipe Qty / كمية الوصفة", "Sold Qty / الكمية المباعة", "Total Consumed / إجمالي الاستهلاك", "Branch / الفرع", "Order Type / نوع الطلب", "Status / الحالة");
            for (var i = 0; i < details.Count; i++) { var row = details[i]; var n = i + 2; sheet.Cell(n, 1).Value = row.DeductedAtUtc.Date; sheet.Cell(n, 2).Value = row.DeductedAtUtc.TimeOfDay; sheet.Cell(n, 3).Value = row.OrderNumber; sheet.Cell(n, 4).Value = Bilingual(row.ProductName, row.ProductNameAr); sheet.Cell(n, 5).Value = Bilingual(row.CategoryName, row.CategoryNameAr); sheet.Cell(n, 6).Value = Bilingual(row.RawMaterialName, row.RawMaterialNameAr); sheet.Cell(n, 7).Value = row.RecipeQuantity; sheet.Cell(n, 8).Value = row.SoldQuantity; sheet.Cell(n, 9).Value = row.TotalConsumed; sheet.Cell(n, 10).Value = Bilingual(row.BranchName, row.BranchNameAr); sheet.Cell(n, 11).Value = row.OrderType; sheet.Cell(n, 12).Value = row.OrderStatus; }
            sheet.RightToLeft = false; Format(sheet);
        }

        private static void WriteFilters(XLWorkbook workbook, RawMaterialConsumptionReportDto report, RawMaterialConsumptionQueryDto query, string generatedBy)
        {
            var sheet = workbook.Worksheets.Add("Applied Filters - عوامل التصفية");
            var rows = new[] { ("Raw Material / المادة الخام", Bilingual(report.RawMaterialName, report.RawMaterialNameAr)), ("From / من", report.FromUtc.ToString("u")), ("To / إلى", report.ToUtc.ToString("u")), ("Branch / الفرع", Bilingual(report.BranchName, report.BranchNameAr)), ("Category ID / الفئة", query.CategoryId?.ToString() ?? "All"), ("Product ID / المنتج", query.ProductId?.ToString() ?? "All"), ("Order Type / نوع الطلب", query.OrderChannel ?? "All"), ("Order Status / حالة الطلب", query.OrderStatus ?? "All"), ("Search / البحث", query.Search ?? ""), ("Generated By / أنشئ بواسطة", generatedBy) };
            Headers(sheet, 1, "Filter / عامل التصفية", "Value / القيمة"); for (var i = 0; i < rows.Length; i++) { sheet.Cell(i + 2, 1).Value = rows[i].Item1; sheet.Cell(i + 2, 2).Value = rows[i].Item2; } Format(sheet);
        }

        private static void Headers(IXLWorksheet sheet, int row, params string[] labels) { for (var i = 0; i < labels.Length; i++) sheet.Cell(row, i + 1).Value = labels[i]; var range = sheet.Range(row, 1, row, labels.Length); range.Style.Font.Bold = true; range.Style.Font.FontColor = XLColor.White; range.Style.Fill.BackgroundColor = XLColor.FromHtml(HeaderColor); }
        private static void Format(IXLWorksheet sheet) { sheet.SheetView.FreezeRows(1); sheet.Columns().AdjustToContents(5, 45); sheet.Columns().Style.Alignment.WrapText = true; sheet.Style.Font.FontName = "Arial"; }
        private static void SetValue(IXLCell cell, object? value) { if (value is DateTime date) cell.Value = date; else if (value is decimal number) cell.Value = number; else if (value is int count) cell.Value = count; else cell.Value = value?.ToString() ?? ""; }
        private static string Bilingual(string english, string? arabic) => string.IsNullOrWhiteSpace(arabic) ? english : $"{english} / {arabic}";
        private static string Csv(string value) => $"\"{value.Replace("\"", "\"\"")}\"";
        private static string FileName(string extension) => $"raw-material-consumption-{DateTime.UtcNow:yyyyMMdd-HHmm}.{extension}";
        private static void AddLogo(IXLWorksheet sheet, string? logoUrl)
        {
            if (string.IsNullOrWhiteSpace(logoUrl) || !logoUrl.StartsWith("data:image/", StringComparison.OrdinalIgnoreCase)) return;
            var separator = logoUrl.IndexOf(','); if (separator < 0) return;
            try { using var stream = new MemoryStream(Convert.FromBase64String(logoUrl[(separator + 1)..])); sheet.AddPicture(stream).MoveTo(sheet.Cell("D1")).Scale(0.35); } catch (FormatException) { }
        }
    }
}
